version: "3.1"
services:
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${ POSTGRESS_PASSWORD }
      POSTGRES_USER: ${ POSTGRESS_USER }
      POSTGRES_DB: ${ POSTGRESS_DB }
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
