export const brandUrl = [
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/chevrolet.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/ford.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/foton.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/hino.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/honda.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/hyundai.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/isuzu.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/jeep.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/kia.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/mazda.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/mercedez bench.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/mitsubishi.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/nissan.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/peugeot.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/subaru.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/suzuki.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/toyota.png",
  "https://tpbrgzfczohtyssijgxb.supabase.co/storage/v1/object/public/vehicle/brands/volkswagen.png",
];
